---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
allowVolumeExpansion: true
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: io2
allowVolumeExpansion: true
provisioner: ebs.csi.aws.com
parameters:
  type: io2
  iopsPerGB: "200"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
